travis:
  secure:
    BINSTAR_TOKEN: qyzHNwGhl/aJyV0CQO5qeT2EUbysoOKZLLB0otRIpUVaN/1gzMfVrvT+2N0pqgevs2lZRzVdZi0TksSr7Pikbucz37xjYicfQuw2vLOUe2S+fSCANFREuURIQ9MLxRZC6RpQKuK/IdiG2YLDhhj9TZVC+1juPVTXtj9CoeP1OJY8HW2TVYsg6Bz34mCUdUsqUcmU06urb2YcpG8+wIgDCHth+GOPVlu3UfRrKj6nBpcwTsSj5YggeXTVYBG88Np25yG5/0XJYrZe3OC4LssaYWzp3PT8ODFbrQFvE/etmQMOnPjE5wDITeqYxviD7TA8a0vQ0EDklINHyra9kjuq8P3OX/yCVUxUgBF7DEHM6DKzMT5mJUDRNqjjXyuk7kkht/8iGNjB6MbBAkey0PlCDv452WuCMvIRmQeW7SPI7H+rePyxsLpoof9GcW9Vf6uQ6GM9IKgpO7JB+gNmAxBxEm9Vhjasc2iusMdaqjNiqDkyGEiNKD1cSwg50IPUQpLunEh+Vq5EtR/VdnyoBhapjEgzrXGRO+KlrU5PoH720nPd5uUmoyi9irdbWgVa686M374EVLNRC4JXl9Tu2/klwsJccEjLkPnYHa2tydoq4VKsOMOQ0+7nEqVtJbonvSKhx+wDuD4jUIB8WX54cUSyvf+F6HP21yUNZhc8sSs/zcA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
