travis:
  secure:
    BINSTAR_TOKEN: PSSFqKujkv58C7E/BJLcwnr0mg9wMtuUL0qpOV9iJUzsikjZdIeuMe5PuPvllqWXPJfQEMK58j+6jet02NUZOKce+tZHbbOJieNIdU2KzYP1ZPI31pOp/zXFpwbiF/faYRL4v+DaepnfZTw7eGwUZizPBpUBQzYoOQgIJjZkKFZi8K4qy71ykfFaESUED3MN+bPHuBA2fAT0Adc13U17b2rJNvNYuJH9NYvHuN2Q7JjCTp/8QOzzBqjScVjtO9arG6kyjPKQYSp2zvG4bO9kiH3+kaus1w8wr4UesuV8f+MmTXth2xOTFO9WPdAoeIoEyZEMMMKspRdr6G78qsNQpl3tsNqj0YyQqNCKiafWh/CtWRh1yCrdjOZdpjLtDDerVxZ8k345GZh+3CIW5pBg3dm9glqLg5adwquRYyfh5GEbM1UwcRXjcCmLGPHWJYIwpqpUTZT2YY1cHumI9wNiC0Pc/x/1+tr+8QzbwmYnM4bTB6ZwIYkC0yjLs1yNy9PJOokCUlaG1sirbgukahoB2B4LMzYApwtc8HzzwDat8NxmjKhgZqU/1Dh8v5W8Yg35/wH+W49zFoSg3icUmtcGuomIeHyKlDQ8QGeM21OvDChmlWDrakrAlvbIA7g6uB950cjy4KZrj/AGuPkommj86U99q6j1NLPjOvxDKqDr2dI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
